clear;
ts = 1/(20e6);
rx = comm.SDRuReceiver(...
              'Platform','B210', ...
              'SerialNum','32339F7', ...
              'CenterFrequency',1485e6, ...
              'MasterClockRate',(1/ts), ...
              'OutputDataType','double', ...
              'Gain',60, ...
              'DecimationFactor',256);

rxLog = dsp.SignalSink;
    for counter = 1:20
        data = rx();
        rxLog(data);
    end
release(rx)
release(rxLog)


