clear;
ts = 1/(20e6);
if(~(exist('rx', 'var')))
    rx = comm.SDRuReceiver(...
                  'Platform','B210', ...
                  'SerialNum','32339F7', ...
                  'CenterFrequency',1485e6, ...
                  'MasterClockRate',(1/ts), ...
                  'OutputDataType','double', ...
                  'Gain',60, ...
                  'DecimationFactor',1,...
                  'EnableBurstMode', 1, ...
                  'NumFramesInBurst', 1e2);
end
rxLog = dsp.SignalSink;
data = rx();
rxLog(data);
release(rx)
data = rxLog.Buffer;
release(rxLog)


